name: Playlist Tracker
on:
  schedule:
    - cron: "0 */6 * * *"  # Alle 6 Stunden
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests

      - name: Run Tracker
        env:
          DISCORD_PLAYLIST_WEBHOOK2: ${{ secrets.DISCORD_PLAYLIST_WEBHOOK2 }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python playlist_tracker.py
