name: Playlist Tracker
on:
  schedule:
    - cron: "0 */6 * * *"  # Alle 6 Stunden
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Daten
        uses: actions/cache@v3
        with:
          path: |
            tracked_playlists.json
            last_telegram_update.txt
          key: playlist-data-${{ hashFiles('tracked_playlists.json', 'last_telegram_update.txt') }}

      - name: Run Tracker
        env:
          DISCORD_PLAYLIST_WEBHOOK2: ${{ secrets.DISCORD_PLAYLIST_WEBHOOK2 }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python playlist_tracker.py
