name: Surreal Release Bot
on:
  schedule:
    - cron: "*/5 * * * *"  # Läuft alle 5 Minuten
  workflow_dispatch:       # Manueller Trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Cache für Datenbanken
        uses: actions/cache@v3
        with:
          path: |
            processed_releases.json
            last_telegram_update.txt
          key: db-${{ hashFiles('processed_releases.json', 'last_telegram_update.txt') }}
          restore-keys: db-

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Abhängigkeiten installieren
        run: pip install requests

      - name: Bot starten
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python surreal_notify.py

      - name: Änderungen committen
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"
          git add processed_releases.json last_telegram_update.txt
          git diff --quiet || (git commit -m "Datenbank aktualisiert" && git push)
