name: Surreal Notifier

on:
  schedule:
    - cron: '*/4 * * * *'  # Alle 4 Minuten für Überlappungsschutz
    - cron: '*/9 * * * *'  # Backup-Trigger alle 9 Minuten
  workflow_dispatch:

permissions:
  contents: write
  actions: read  # Für Cache-Zugriff

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Verhindert Hänger

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Lockfile erstellen
        run: echo "${{ github.run_id }}" > .github/.lock

      - name: Parallelitätskontrolle
        uses: nrwl/workspace-lock@v1
        with:
          path: .github/.lock

      - name: Tracking-Dateien initialisieren
        run: |
          mkdir -p db
          [ -f db/processed_releases.json ] || echo '{"processed":[]}' > db/processed_releases.json
          [ -f db/last_telegram_update.txt ] || echo "0" > db/last_telegram_update.txt

      - name: Cache für Datenbanken
        uses: actions/cache@v3
        with:
          path: db/
          key: db-${{ hashFiles('db/processed_releases.json', 'db/last_telegram_update.txt') }}
          restore-keys: db-

      - name: Python-Umgebung
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Abhängigkeiten
        run: pip install requests python-dotenv

      - name: Bot-Lauf mit Wiederholung
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          for i in {1..3}; do
            python surreal_notify.py
            if [ $? -eq 0 ]; then
              break
            else
              echo "Versuch $i fehlgeschlagen, wiederhole in 30s..."
              sleep 30
            fi
          done

      - name: Commit-Sicherung
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Notfall-Backup: ${{ github.run_id }}" || echo "Keine Änderungen"
          git push origin HEAD:main || echo "Push fehlgeschlagen"
          
      - name: Lockfile entfernen
        if: always()
        run: rm -f .github/.lock
