name: Surreal Notifier

on:
  schedule:
    - cron: '*/4 * * * *'  # Primärer Trigger
    - cron: '*/9 * * * *'  # Backup-Trigger
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Stoppt überlappende Läufe

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Tracking-Dateien initialisieren
        run: |
          mkdir -p db
          [ -f db/processed_releases.json ] || echo '{"processed":[]}' > db/processed_releases.json
          [ -f db/last_telegram_update.txt ] || echo "0" > db/last_telegram_update.txt

      - name: Cache für Datenbanken
        uses: actions/cache@v3
        with:
          path: db/
          key: db-${{ hashFiles('db/processed_releases.json', 'db/last_telegram_update.txt') }}
          restore-keys: db-

      - name: Python-Umgebung
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Abhängigkeiten
        run: pip install requests

      - name: Bot-Lauf mit Wiederholung
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          for i in {1..3}; do
            python surreal_notify.py
            if [ $? -eq 0 ]; then
              exit 0
            fi
            echo "Versuch $i fehlgeschlagen, wiederhole in 15s..."
            sleep 15
          done
          exit 1

      - name: Änderungen committen
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Automatisches Update [skip ci]" || echo "Keine Änderungen"
          git pull --rebase
          git push origin HEAD:main
