name: Surreal Notifier

on:
  schedule:
    - cron: '*/5 * * * *'  # Alle 5 Minuten
  workflow_dispatch:  # Optional für manuellen Start

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Verhindert Hänger

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Python 3.10 installieren
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Abhängigkeiten installieren
        run: pip install requests

      - name: Datenbank initialisieren
        run: |
          mkdir -p db
          if [ ! -f db/processed_releases.json ]; then
            echo '{"processed": []}' > db/processed_releases.json
          fi
          if [ ! -f db/last_telegram_update.txt ]; then
            echo "0" > db/last_telegram_update.txt
          fi

      - name: Bot ausführen
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python surreal_notify.py

      - name: Änderungen committen
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"
          git add db/
          git commit -m "Automatisches Update: $(date +'%Y-%m-%d %H:%M')" || echo "Keine Änderungen"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}.git
          git pull --rebase
          git push origin HEAD:main
