name: Surreal Notifier

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache für Datenbanken
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            processed_releases.json
            last_telegram_update.txt
          key: db-${{ hashFiles('processed_releases.json', 'last_telegram_update.txt') }}
          restore-keys: db-

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: pip install requests

      - name: Bot starten
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python surreal_notify.py

      - name: Änderungen committen
        if: always()
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "github-actions@example.com"
          
          # Nur committen wenn es Änderungen gibt
          git add processed_releases.json last_telegram_update.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update tracking files"
          git push
