name: Surreal Notifier

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # Für korrekte Git-Historie

      - name: Tracking-Dateien initialisieren
        run: |
          if [ ! -f processed_releases.json ]; then echo "[]" > processed_releases.json; fi
          if [ ! -f last_telegram_update.txt ]; then echo "0" > last_telegram_update.txt; fi

      - name: Cache für Datenbanken
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            processed_releases.json
            last_telegram_update.txt
          key: db-${{ hashFiles('processed_releases.json', 'last_telegram_update.txt') }}
          restore-keys: |
            db-

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: pip install requests

      - name: Bot starten
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python surreal_notify.py

      - name: Änderungen committen
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add processed_releases.json last_telegram_update.txt
          
          if ! git diff --staged --quiet; then
            git commit -m "Automatisches Update der Tracking-Daten"
            git pull --rebase  # Konflikte vermeiden
            git push origin HEAD:main
          else
            echo "Keine Änderungen zum Committen"
          fi
